In [1]:
import numpy as np
import pandas as pd

In [8]:
a = np.array([1,5,3,3,9,7,7])
a

array([1, 5, 3, 3, 9, 7, 7])

In [9]:
i=a.argmax()
a[i]

9

In [15]:
b = np.unique(a , return_counts=True, return_index=True)

In [16]:
b

(array([1, 3, 5, 7, 9]),
 array([0, 2, 1, 5, 4], dtype=int64),
 array([1, 2, 1, 2, 1], dtype=int64))

In [17]:
type(b)

tuple

In [31]:
a = [[6,0],[3,1],[4,1],[8,0],[7,0]]
#a = np.array(a)

In [34]:
a = sorted(a)
a

[[3, 1], [4, 1], [6, 0], [7, 0], [8, 0]]

In [37]:
a = a[:3]
print(a)
a = np.array(a)
print(a)

[[3, 1], [4, 1], [6, 0]]
[[3 1]
 [4 1]
 [6 0]]


In [38]:
b = np.unique(a[:,1], return_counts=True)

In [39]:
b

(array([0, 1]), array([1, 2], dtype=int64))

In [48]:
c=b[1]
i=c.argmax()
b[0][i]

1

In [65]:
a = np.array([1,2,3])
b = np.array([6,7,8])
dist = sum(a-b)

In [66]:
dist

-15

In [202]:
x = pd.read_csv('xdata.csv')
y = pd.read_csv('ydata.csv')

x = x.drop('0', axis=1).values
y = y.drop('0',axis=1).values

In [203]:
x

array([[ 3.516279  ,  3.71975047],
       [ 4.60649561,  3.41437943],
       [ 4.67701056,  3.04724443],
       [ 4.15772454,  3.13867678],
       [ 3.15443087,  3.61985805],
       [ 3.41751854,  4.59164128],
       [ 1.61124605,  3.39835595],
       [ 4.28808719,  4.04396943],
       [ 3.19607968,  4.95114323],
       [ 1.6258394 ,  4.90239967],
       [ 2.82894521,  3.91445026],
       [ 2.28966729,  5.06896877],
       [ 2.89206152,  3.66529487],
       [ 2.33634919,  4.77256166],
       [ 3.67027475,  3.79730296],
       [ 2.30717865,  4.73262822],
       [ 3.15130599,  3.43648588],
       [ 4.14502484,  2.94851846],
       [ 2.17253471,  3.6488889 ],
       [ 3.39390371,  4.13447274],
       [ 1.59644351,  4.43875703],
       [ 3.38348549,  4.02119623],
       [ 5.08330979,  4.03477733],
       [ 1.21644435,  4.31174386],
       [ 4.15939179,  2.54939222],
       [ 2.2392529 ,  4.33673035],
       [ 2.99918423,  5.63946256],
       [ 3.10384641,  3.0156258 ],
       [ 2.47612428,

In [204]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [205]:
def distance(a,b):
    dist = np.sqrt(sum(a-b)**2)
    return dist

In [206]:
def KNN(x,y,querry, k=7):
    m = x.shape[0]
    n = querry.shape[0]
    predict=[]
    for j in range(n):
        dist=[]
        for i in range(m):
            d = distance(x[i], querry[j])
            dist.append([d,y[i][0]])            ## here y is 2D...
        sort_dist = sorted(dist)
        sort_dist = sort_dist[:7]
        sort_dist = np.array(sort_dist)
        no_of_label = np.unique(sort_dist[:,1], return_counts=True)
        index = no_of_label[1].argmax()
        predict.append([querry[j], no_of_label[0][index]])
    return predict    

In [207]:
x_train = x[0:int(x.shape[0]*0.7)]
x_test = x[int(x.shape[0]*0.7):]

y_train = y[0:int(x.shape[0]*0.7)]
y_test = y[int(x.shape[0]*0.7):]

In [208]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((279, 2), (279, 1), (120, 2), (120, 1))

In [209]:
predict = KNN(x_train,y_train,x_test)

In [210]:
predict

[[array([0.35313046, 2.58971674]), 1.0],
 [array([0.52991511, 0.73730215]), 1.0],
 [array([-0.68851096,  0.44992686]), 1.0],
 [array([-0.43366679, -0.03749477]), 1.0],
 [array([-1.21056762, -0.3103894 ]), 1.0],
 [array([-0.16276547,  0.3482789 ]), 1.0],
 [array([0.63869619, 0.12579976]), 1.0],
 [array([-1.11418101,  0.34021499]), 1.0],
 [array([-0.29015181, -0.19005801]), 1.0],
 [array([0.43666721, 1.05481581]), 1.0],
 [array([-0.42100349, -0.19149351]), 1.0],
 [array([-0.99230651,  0.83544424]), 1.0],
 [array([-0.17874325,  1.20829439]), 1.0],
 [array([-0.88861105,  0.78937675]), 1.0],
 [array([0.16099552, 1.50604104]), 1.0],
 [array([-1.27588892, -0.16940926]), 1.0],
 [array([-0.73552512, -0.12297833]), 1.0],
 [array([-3.1271992 , -0.72069566]), 1.0],
 [array([-0.11784564,  0.95187713]), 1.0],
 [array([0.56485281, 0.90053776]), 1.0],
 [array([0.19901465, 1.32580617]), 1.0],
 [array([-0.44147835,  0.0083557 ]), 1.0],
 [array([-1.22127101,  0.65153281]), 1.0],
 [array([0.75670456, 1.84

In [211]:
b = np.unique(y_train, return_counts=True)
b

(array([0., 1.]), array([199,  80], dtype=int64))

In [212]:
def score(x,y):
    count=0
    for i in range(len(y)):
        if x[i][1]==y[i]:
            count=count+1
    print(count)
    print(count/len(y))
    print('\n')
    print(count/len(y)*100)
    

In [213]:
score(predict, y_test)

119
0.9916666666666667


99.16666666666667


__Titanic Dataset with Skretch KNN:__

In [62]:
train = pd.read_csv('titanic_train.csv')
test = pd.read_csv('titanic_test.csv')
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [63]:
train.drop(['PassengerId','Name','Ticket','Cabin'], axis=1, inplace=True)
train.head(n=10)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S
5         0       3    male   NaN      0      0   8.4583        Q
6         0       1    male  54.0      0      0  51.8625        S
7         0       3    male   2.0      3      1  21.0750        S
8         1       3  female  27.0      0      2  11.1333        S
9         1       2  female  14.0      1      0  30.0708        C

In [64]:
train = train.fillna({"Age":train["Age"].mean()})
train

Survived  Pclass     Sex        Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.000000      1      0    7.2500        S
1           1       1  female  38.000000      1      0   71.2833        C
2           1       3  female  26.000000      0      0    7.9250        S
3           1       1  female  35.000000      1      0   53.1000        S
4           0       3    male  35.000000      0      0    8.0500        S
5           0       3    male  29.699118      0      0    8.4583        Q
6           0       1    male  54.000000      0      0   51.8625        S
7           0       3    male   2.000000      3      1   21.0750        S
8           1       3  female  27.000000      0      2   11.1333        S
9           1       2  female  14.000000      1      0   30.0708        C
10          1       3  female   4.000000      1      1   16.7000        S
11          1       1  female  58.000000      0      0   26.5500        S
12          0       3    male  20.000000      0      0    8.0500        S
13          0       3    male  39.000000      1      5   31.2750        S
14          0       3  female  14.000000      0      0    7.8542        S
15          1       2  female  55.000000      0      0   16.0000        S
16          0       3    male   2.000000      4      1   29.1250        Q
17          1       2    male  29.699118      0      0   13.0000        S
18          0       3  female  31.000000      1      0   18.0000        S
19          1       3  female  29.699118      0      0    7.2250        C
20          0       2    male  35.000000      0      0   26.0000        S
21          1       2    male  34.000000      0      0   13.0000        S
22          1       3  female  15.000000      0      0    8.0292        Q
23          1       1    male  28.000000      0      0   35.5000        S
24          0       3  female   8.000000      3      1   21.0750        S
25          1       3  female  38.000000      1      5   31.3875        S
26          0       3    male  29.699118      0      0    7.2250        C
27          0       1    male  19.000000      3      2  263.0000        S
28          1       3  female  29.699118      0      0    7.8792        Q
29          0       3    male  29.699118      0      0    7.8958        S
..        ...     ...     ...        ...    ...    ...       ...      ...
861         0       2    male  21.000000      1      0   11.5000        S
862         1       1  female  48.000000      0      0   25.9292        S
863         0       3  female  29.699118      8      2   69.5500        S
864         0       2    male  24.000000      0      0   13.0000        S
865         1       2  female  42.000000      0      0   13.0000        S
866         1       2  female  27.000000      1      0   13.8583        C
867         0       1    male  31.000000      0      0   50.4958        S
868         0       3    male  29.699118      0      0    9.5000        S
869         1       3    male   4.000000      1      1   11.1333        S
870         0       3    male  26.000000      0      0    7.8958        S
871         1       1  female  47.000000      1      1   52.5542        S
872         0       1    male  33.000000      0      0    5.0000        S
873         0       3    male  47.000000      0      0    9.0000        S
874         1       2  female  28.000000      1      0   24.0000        C
875         1       3  female  15.000000      0      0    7.2250        C
876         0       3    male  20.000000      0      0    9.8458        S
877         0       3    male  19.000000      0      0    7.8958        S
878         0       3    male  29.699118      0      0    7.8958        S
879         1       1  female  56.000000      0      1   83.1583        C
880         1       2  female  25.000000      0      1   26.0000        S
881         0       3    male  33.000000      0      0    7.8958        S
882         0       3  female  22.000000      0      0   10.5167        S
883      

In [67]:
train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [66]:
train.dropna(inplace=True)
train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [68]:
## Labeling in the sex column......
l=[]
def convert_sex(sex):
    #print(sex)
    for i in sex:
        if i=='male':
            l.append(1)
        else:
            l.append(0)
convert_sex(train["Sex"])
train["Sex"]=l
train

Survived  Pclass  Sex        Age  SibSp  Parch      Fare Embarked
0           0       3    1  22.000000      1      0    7.2500        S
1           1       1    0  38.000000      1      0   71.2833        C
2           1       3    0  26.000000      0      0    7.9250        S
3           1       1    0  35.000000      1      0   53.1000        S
4           0       3    1  35.000000      0      0    8.0500        S
5           0       3    1  29.699118      0      0    8.4583        Q
6           0       1    1  54.000000      0      0   51.8625        S
7           0       3    1   2.000000      3      1   21.0750        S
8           1       3    0  27.000000      0      2   11.1333        S
9           1       2    0  14.000000      1      0   30.0708        C
10          1       3    0   4.000000      1      1   16.7000        S
11          1       1    0  58.000000      0      0   26.5500        S
12          0       3    1  20.000000      0      0    8.0500        S
13          0       3    1  39.000000      1      5   31.2750        S
14          0       3    0  14.000000      0      0    7.8542        S
15          1       2    0  55.000000      0      0   16.0000        S
16          0       3    1   2.000000      4      1   29.1250        Q
17          1       2    1  29.699118      0      0   13.0000        S
18          0       3    0  31.000000      1      0   18.0000        S
19          1       3    0  29.699118      0      0    7.2250        C
20          0       2    1  35.000000      0      0   26.0000        S
21          1       2    1  34.000000      0      0   13.0000        S
22          1       3    0  15.000000      0      0    8.0292        Q
23          1       1    1  28.000000      0      0   35.5000        S
24          0       3    0   8.000000      3      1   21.0750        S
25          1       3    0  38.000000      1      5   31.3875        S
26          0       3    1  29.699118      0      0    7.2250        C
27          0       1    1  19.000000      3      2  263.0000        S
28          1       3    0  29.699118      0      0    7.8792        Q
29          0       3    1  29.699118      0      0    7.8958        S
..        ...     ...  ...        ...    ...    ...       ...      ...
861         0       2    1  21.000000      1      0   11.5000        S
862         1       1    0  48.000000      0      0   25.9292        S
863         0       3    0  29.699118      8      2   69.5500        S
864         0       2    1  24.000000      0      0   13.0000        S
865         1       2    0  42.000000      0      0   13.0000        S
866         1       2    0  27.000000      1      0   13.8583        C
867         0       1    1  31.000000      0      0   50.4958        S
868         0       3    1  29.699118      0      0    9.5000        S
869         1       3    1   4.000000      1      1   11.1333        S
870         0       3    1  26.000000      0      0    7.8958        S
871         1       1    0  47.000000      1      1   52.5542        S
872         0       1    1  33.000000      0      0    5.0000        S
873         0       3    1  47.000000      0      0    9.0000        S
874         1       2    0  28.000000      1      0   24.0000        C
875         1       3    0  15.000000      0      0    7.2250        C
876         0       3    1  20.000000      0      0    9.8458        S
877         0       3    1  19.000000      0      0    7.8958        S
878         0       3    1  29.699118      0      0    7.8958        S
879         1       1    0  56.000000      0      1   83.1583        C
880         1       2    0  25.000000      0      1   26.0000        S
881         0       3    1  33.000000      0      0    7.8958        S
882         0       3    0  22.000000      0      0   10.5167        S
883         0       2    1  28.000000      0      0   10.5000        S
884         0       3    1  25.000000      0      0    7.0500        S
885         0       3    0  3

In [69]:
## Labeling the Embarked column....
ls=[]
def convert_em(embarked):
   # print(embarked)
    for i in embarked:
        if i=="S":
            ls.append(1)
        elif i=="C":
            ls.append(2)
        else:
            ls.append(3)
convert_em(train['Embarked'])
train["Embarked"]=ls
train

Survived  Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
0           0       3    1  22.000000      1      0    7.2500         1
1           1       1    0  38.000000      1      0   71.2833         2
2           1       3    0  26.000000      0      0    7.9250         1
3           1       1    0  35.000000      1      0   53.1000         1
4           0       3    1  35.000000      0      0    8.0500         1
5           0       3    1  29.699118      0      0    8.4583         3
6           0       1    1  54.000000      0      0   51.8625         1
7           0       3    1   2.000000      3      1   21.0750         1
8           1       3    0  27.000000      0      2   11.1333         1
9           1       2    0  14.000000      1      0   30.0708         2
10          1       3    0   4.000000      1      1   16.7000         1
11          1       1    0  58.000000      0      0   26.5500         1
12          0       3    1  20.000000      0      0    8.0500         1
13          0       3    1  39.000000      1      5   31.2750         1
14          0       3    0  14.000000      0      0    7.8542         1
15          1       2    0  55.000000      0      0   16.0000         1
16          0       3    1   2.000000      4      1   29.1250         3
17          1       2    1  29.699118      0      0   13.0000         1
18          0       3    0  31.000000      1      0   18.0000         1
19          1       3    0  29.699118      0      0    7.2250         2
20          0       2    1  35.000000      0      0   26.0000         1
21          1       2    1  34.000000      0      0   13.0000         1
22          1       3    0  15.000000      0      0    8.0292         3
23          1       1    1  28.000000      0      0   35.5000         1
24          0       3    0   8.000000      3      1   21.0750         1
25          1       3    0  38.000000      1      5   31.3875         1
26          0       3    1  29.699118      0      0    7.2250         2
27          0       1    1  19.000000      3      2  263.0000         1
28          1       3    0  29.699118      0      0    7.8792         3
29          0       3    1  29.699118      0      0    7.8958         1
..        ...     ...  ...        ...    ...    ...       ...       ...
861         0       2    1  21.000000      1      0   11.5000         1
862         1       1    0  48.000000      0      0   25.9292         1
863         0       3    0  29.699118      8      2   69.5500         1
864         0       2    1  24.000000      0      0   13.0000         1
865         1       2    0  42.000000      0      0   13.0000         1
866         1       2    0  27.000000      1      0   13.8583         2
867         0       1    1  31.000000      0      0   50.4958         1
868         0       3    1  29.699118      0      0    9.5000         1
869         1       3    1   4.000000      1      1   11.1333         1
870         0       3    1  26.000000      0      0    7.8958         1
871         1       1    0  47.000000      1      1   52.5542         1
872         0       1    1  33.000000      0      0    5.0000         1
873         0       3    1  47.000000      0      0    9.0000         1
874         1       2    0  28.000000      1      0   24.0000         2
875         1       3    0  15.000000      0      0    7.2250         2
876         0       3    1  20.000000      0      0    9.8458         1
877         0       3    1  19.000000      0      0    7.8958         1
878         0       3    1  29.699118      0      0    7.8958         1
879         1       1    0  56.000000      0      1   83.1583         2
880         1       2    0  25.000000      0      1   26.0000         1
881         0       3    1  33.000000      0      0    7.8958         1
882         0       3    0  22.000000      0      0   10.5167         1
883         0       2    1  28.000000      0      0   10.5000         1
884         0       3    1  25.000000      0 

In [70]:
train["Embarked"].dtype , train["Sex"].dtype

(dtype('int64'), dtype('int64'))

In [71]:
test.drop(['PassengerId','Name','Ticket','Cabin'], axis=1, inplace=True)
test.head(n=10)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S
5       3    male  14.0      0      0   9.2250        S
6       3  female  30.0      0      0   7.6292        Q
7       2    male  26.0      1      1  29.0000        S
8       3  female  18.0      0      0   7.2292        C
9       3    male  21.0      2      0  24.1500        S

In [72]:
test = test.fillna({"Age":test["Age"].mean()})
test

Pclass     Sex       Age  SibSp  Parch      Fare Embarked
0         3    male  34.50000      0      0    7.8292        Q
1         3  female  47.00000      1      0    7.0000        S
2         2    male  62.00000      0      0    9.6875        Q
3         3    male  27.00000      0      0    8.6625        S
4         3  female  22.00000      1      1   12.2875        S
5         3    male  14.00000      0      0    9.2250        S
6         3  female  30.00000      0      0    7.6292        Q
7         2    male  26.00000      1      1   29.0000        S
8         3  female  18.00000      0      0    7.2292        C
9         3    male  21.00000      2      0   24.1500        S
10        3    male  30.27259      0      0    7.8958        S
11        1    male  46.00000      0      0   26.0000        S
12        1  female  23.00000      1      0   82.2667        S
13        2    male  63.00000      1      0   26.0000        S
14        1  female  47.00000      1      0   61.1750        S
15        2  female  24.00000      1      0   27.7208        C
16        2    male  35.00000      0      0   12.3500        Q
17        3    male  21.00000      0      0    7.2250        C
18        3  female  27.00000      1      0    7.9250        S
19        3  female  45.00000      0      0    7.2250        C
20        1    male  55.00000      1      0   59.4000        C
21        3    male   9.00000      0      1    3.1708        S
22        1  female  30.27259      0      0   31.6833        S
23        1    male  21.00000      0      1   61.3792        C
24        1  female  48.00000      1      3  262.3750        C
25        3    male  50.00000      1      0   14.5000        S
26        1  female  22.00000      0      1   61.9792        C
27        3    male  22.50000      0      0    7.2250        C
28        1    male  41.00000      0      0   30.5000        S
29        3    male  30.27259      2      0   21.6792        C
..      ...     ...       ...    ...    ...       ...      ...
388       3    male  21.00000      0      0    7.7500        Q
389       3    male   6.00000      3      1   21.0750        S
390       1    male  23.00000      0      0   93.5000        S
391       1  female  51.00000      0      1   39.4000        S
392       3    male  13.00000      0      2   20.2500        S
393       2    male  47.00000      0      0   10.5000        S
394       3    male  29.00000      3      1   22.0250        S
395       1  female  18.00000      1      0   60.0000        S
396       3    male  24.00000      0      0    7.2500        Q
397       1  female  48.00000      1      1   79.2000        C
398       3    male  22.00000      0      0    7.7750        S
399       3    male  31.00000      0      0    7.7333        Q
400       1  female  30.00000      0      0  164.8667        S
401       2    male  38.00000      1      0   21.0000        S
402       1  female  22.00000      0      1   59.4000        C
403       1    male  17.00000      0      0   47.1000        S
404       1    male  43.00000      1      0   27.7208        C
405       2    male  20.00000      0      0   13.8625        C
406       2    male  23.00000      1      0   10.5000        S
407       1    male  50.00000      1      1  211.5000        C
408       3  female  30.27259      0      0    7.7208        Q
409       3  female   3.00000      1      1   13.7750        S
410       3  female  30.27259      0      0    7.7500        Q
411       1  female  37.00000      1      0   90.0000        Q
412       3  female  28.00000      0      0    7.7750        S
413       3    male  30.27259      0      0    8.0500        S
414       1  female  39.00000      0      0  108.9000        C
415       3    male  38.50000      0      0    7.2500        S
416       3    male  30.27259      0      0    8.0500        S
417       3    male  30.27259      1      1   22.3583        C

[418 rows x 7 columns]

In [73]:
## Labeling in the sex column......
l=[]
def convert_sex(sex):
    #print(sex)
    for i in sex:
        if i=='male':
            l.append(1)
        else:
            l.append(0)
convert_sex(test["Sex"])
test["Sex"]=l
test

Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0         3    1  34.50000      0      0    7.8292        Q
1         3    0  47.00000      1      0    7.0000        S
2         2    1  62.00000      0      0    9.6875        Q
3         3    1  27.00000      0      0    8.6625        S
4         3    0  22.00000      1      1   12.2875        S
5         3    1  14.00000      0      0    9.2250        S
6         3    0  30.00000      0      0    7.6292        Q
7         2    1  26.00000      1      1   29.0000        S
8         3    0  18.00000      0      0    7.2292        C
9         3    1  21.00000      2      0   24.1500        S
10        3    1  30.27259      0      0    7.8958        S
11        1    1  46.00000      0      0   26.0000        S
12        1    0  23.00000      1      0   82.2667        S
13        2    1  63.00000      1      0   26.0000        S
14        1    0  47.00000      1      0   61.1750        S
15        2    0  24.00000      1      0   27.7208        C
16        2    1  35.00000      0      0   12.3500        Q
17        3    1  21.00000      0      0    7.2250        C
18        3    0  27.00000      1      0    7.9250        S
19        3    0  45.00000      0      0    7.2250        C
20        1    1  55.00000      1      0   59.4000        C
21        3    1   9.00000      0      1    3.1708        S
22        1    0  30.27259      0      0   31.6833        S
23        1    1  21.00000      0      1   61.3792        C
24        1    0  48.00000      1      3  262.3750        C
25        3    1  50.00000      1      0   14.5000        S
26        1    0  22.00000      0      1   61.9792        C
27        3    1  22.50000      0      0    7.2250        C
28        1    1  41.00000      0      0   30.5000        S
29        3    1  30.27259      2      0   21.6792        C
..      ...  ...       ...    ...    ...       ...      ...
388       3    1  21.00000      0      0    7.7500        Q
389       3    1   6.00000      3      1   21.0750        S
390       1    1  23.00000      0      0   93.5000        S
391       1    0  51.00000      0      1   39.4000        S
392       3    1  13.00000      0      2   20.2500        S
393       2    1  47.00000      0      0   10.5000        S
394       3    1  29.00000      3      1   22.0250        S
395       1    0  18.00000      1      0   60.0000        S
396       3    1  24.00000      0      0    7.2500        Q
397       1    0  48.00000      1      1   79.2000        C
398       3    1  22.00000      0      0    7.7750        S
399       3    1  31.00000      0      0    7.7333        Q
400       1    0  30.00000      0      0  164.8667        S
401       2    1  38.00000      1      0   21.0000        S
402       1    0  22.00000      0      1   59.4000        C
403       1    1  17.00000      0      0   47.1000        S
404       1    1  43.00000      1      0   27.7208        C
405       2    1  20.00000      0      0   13.8625        C
406       2    1  23.00000      1      0   10.5000        S
407       1    1  50.00000      1      1  211.5000        C
408       3    0  30.27259      0      0    7.7208        Q
409       3    0   3.00000      1      1   13.7750        S
410       3    0  30.27259      0      0    7.7500        Q
411       1    0  37.00000      1      0   90.0000        Q
412       3    0  28.00000      0      0    7.7750        S
413       3    1  30.27259      0      0    8.0500        S
414       1    0  39.00000      0      0  108.9000        C
415       3    1  38.50000      0      0    7.2500        S
416       3    1  30.27259      0      0    8.0500        S
417       3    1  30.27259      1      1   22.3583        C

[418 rows x 7 columns]

In [74]:
## Labeling the Embarked column....
ls=[]
def convert_em(embarked):
   # print(embarked)
    for i in embarked:
        if i=="S":
            ls.append(1)
        elif i=="C":
            ls.append(2)
        else:
            ls.append(3)
convert_em(test['Embarked'])
test["Embarked"]=ls
test

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1  34.50000      0      0    7.8292         3
1         3    0  47.00000      1      0    7.0000         1
2         2    1  62.00000      0      0    9.6875         3
3         3    1  27.00000      0      0    8.6625         1
4         3    0  22.00000      1      1   12.2875         1
5         3    1  14.00000      0      0    9.2250         1
6         3    0  30.00000      0      0    7.6292         3
7         2    1  26.00000      1      1   29.0000         1
8         3    0  18.00000      0      0    7.2292         2
9         3    1  21.00000      2      0   24.1500         1
10        3    1  30.27259      0      0    7.8958         1
11        1    1  46.00000      0      0   26.0000         1
12        1    0  23.00000      1      0   82.2667         1
13        2    1  63.00000      1      0   26.0000         1
14        1    0  47.00000      1      0   61.1750         1
15        2    0  24.00000      1      0   27.7208         2
16        2    1  35.00000      0      0   12.3500         3
17        3    1  21.00000      0      0    7.2250         2
18        3    0  27.00000      1      0    7.9250         1
19        3    0  45.00000      0      0    7.2250         2
20        1    1  55.00000      1      0   59.4000         2
21        3    1   9.00000      0      1    3.1708         1
22        1    0  30.27259      0      0   31.6833         1
23        1    1  21.00000      0      1   61.3792         2
24        1    0  48.00000      1      3  262.3750         2
25        3    1  50.00000      1      0   14.5000         1
26        1    0  22.00000      0      1   61.9792         2
27        3    1  22.50000      0      0    7.2250         2
28        1    1  41.00000      0      0   30.5000         1
29        3    1  30.27259      2      0   21.6792         2
..      ...  ...       ...    ...    ...       ...       ...
388       3    1  21.00000      0      0    7.7500         3
389       3    1   6.00000      3      1   21.0750         1
390       1    1  23.00000      0      0   93.5000         1
391       1    0  51.00000      0      1   39.4000         1
392       3    1  13.00000      0      2   20.2500         1
393       2    1  47.00000      0      0   10.5000         1
394       3    1  29.00000      3      1   22.0250         1
395       1    0  18.00000      1      0   60.0000         1
396       3    1  24.00000      0      0    7.2500         3
397       1    0  48.00000      1      1   79.2000         2
398       3    1  22.00000      0      0    7.7750         1
399       3    1  31.00000      0      0    7.7333         3
400       1    0  30.00000      0      0  164.8667         1
401       2    1  38.00000      1      0   21.0000         1
402       1    0  22.00000      0      1   59.4000         2
403       1    1  17.00000      0      0   47.1000         1
404       1    1  43.00000      1      0   27.7208         2
405       2    1  20.00000      0      0   13.8625         2
406       2    1  23.00000      1      0   10.5000         1
407       1    1  50.00000      1      1  211.5000         2
408       3    0  30.27259      0      0    7.7208         3
409       3    0   3.00000      1      1   13.7750         1
410       3    0  30.27259      0      0    7.7500         3
411       1    0  37.00000      1      0   90.0000         3
412       3    0  28.00000      0      0    7.7750         1
413       3    1  30.27259      0      0    8.0500         1
414       1    0  39.00000      0      0  108.9000         2
415       3    1  38.50000      0      0    7.2500         1
416       3    1  30.27259      0      0    8.0500         1
417       3    1  30.27259      1      1   22.3583         2

[418 rows x 7 columns]

In [75]:
test["Embarked"].dtype, test["Sex"].dtype

(dtype('int64'), dtype('int64'))

In [78]:
test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [77]:
test.dropna(inplace=True)

In [136]:
x = train.drop('Survived', axis=1)
y = train['Survived']

x_train = x.values
y_train = y.values
x_test = test.values

In [137]:
x_train

array([[ 3.        ,  1.        , 22.        , ...,  0.        ,
         7.25      ,  1.        ],
       [ 1.        ,  0.        , 38.        , ...,  0.        ,
        71.2833    ,  2.        ],
       [ 3.        ,  0.        , 26.        , ...,  0.        ,
         7.925     ,  1.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, ...,  2.        ,
        23.45      ,  1.        ],
       [ 1.        ,  1.        , 26.        , ...,  0.        ,
        30.        ,  2.        ],
       [ 3.        ,  1.        , 32.        , ...,  0.        ,
         7.75      ,  3.        ]])

In [138]:
x_test

array([[ 3.        ,  1.        , 34.5       , ...,  0.        ,
         7.8292    ,  3.        ],
       [ 3.        ,  0.        , 47.        , ...,  0.        ,
         7.        ,  1.        ],
       [ 2.        ,  1.        , 62.        , ...,  0.        ,
         9.6875    ,  3.        ],
       ...,
       [ 3.        ,  1.        , 38.5       , ...,  0.        ,
         7.25      ,  1.        ],
       [ 3.        ,  1.        , 30.27259036, ...,  0.        ,
         8.05      ,  1.        ],
       [ 3.        ,  1.        , 30.27259036, ...,  1.        ,
        22.3583    ,  2.        ]])

In [139]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [140]:
def distance(a,b):
    dist = np.sqrt(sum(a-b)**2)
    return dist

In [141]:
def KNN(x,y,querry, k=7):
    m = x.shape[0]
    n = querry.shape[0]
    predict=[]
    for j in range(n):
        dist =[]
        for i in range(m):
            d = distance(x[i], querry[j])
            dist.append([d,y[i]])                ## here y is 1D...
        sort_dist = sorted(dist)
        sort_dist = sort_dist[:7]
        sort_dist = np.array(sort_dist)
        no_of_label = np.unique(sort_dist[:,1], return_counts=True)
        index = no_of_label[1].argmax()
        predict.append([querry[j], no_of_label[0][index]])
    return predict    

In [142]:
x_train.shape , y_train.shape , x_test.shape

((889, 7), (889,), (417, 7))

In [143]:
predict = KNN(x_train,y_train,x_test)

In [144]:
predict

[[array([ 3.    ,  1.    , 34.5   ,  0.    ,  0.    ,  7.8292,  3.    ]), 0.0],
 [array([ 3.,  0., 47.,  1.,  0.,  7.,  1.]), 1.0],
 [array([ 2.    ,  1.    , 62.    ,  0.    ,  0.    ,  9.6875,  3.    ]), 1.0],
 [array([ 3.    ,  1.    , 27.    ,  0.    ,  0.    ,  8.6625,  1.    ]), 0.0],
 [array([ 3.    ,  0.    , 22.    ,  1.    ,  1.    , 12.2875,  1.    ]), 0.0],
 [array([ 3.   ,  1.   , 14.   ,  0.   ,  0.   ,  9.225,  1.   ]), 1.0],
 [array([ 3.    ,  0.    , 30.    ,  0.    ,  0.    ,  7.6292,  3.    ]), 1.0],
 [array([ 2.,  1., 26.,  1.,  1., 29.,  1.]), 0.0],
 [array([ 3.    ,  0.    , 18.    ,  0.    ,  0.    ,  7.2292,  2.    ]), 0.0],
 [array([ 3.  ,  1.  , 21.  ,  2.  ,  0.  , 24.15,  1.  ]), 0.0],
 [array([ 3.        ,  1.        , 30.27259036,  0.        ,  0.        ,
          7.8958    ,  1.        ]), 0.0],
 [array([ 1.,  1., 46.,  0.,  0., 26.,  1.]), 0.0],
 [array([ 1.    ,  0.    , 23.    ,  1.    ,  0.    , 82.2667,  1.    ]), 0.0],
 [array([ 2.,  1., 63.,  1.,

In [169]:
new_predict=[]
for i in range(len(predict)):
    new_predict.append(predict[i][1])

prediction = pd.DataFrame(data=new_predict, columns=['predict'])

In [170]:
prediction

predict
0        0.0
1        1.0
2        1.0
3        0.0
4        0.0
5        1.0
6        1.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       1.0
14       1.0
15       0.0
16       0.0
17       0.0
18       0.0
19       0.0
20       1.0
21       1.0
22       0.0
23       0.0
24       1.0
25       0.0
26       0.0
27       0.0
28       0.0
29       0.0
..       ...
387      0.0
388      0.0
389      1.0
390      1.0
391      0.0
392      0.0
393      0.0
394      0.0
395      0.0
396      1.0
397      0.0
398      0.0
399      1.0
400      0.0
401      0.0
402      0.0
403      0.0
404      0.0
405      0.0
406      1.0
407      1.0
408      1.0
409      1.0
410      1.0
411      0.0
412      0.0
413      1.0
414      1.0
415      0.0
416      0.0

[417 rows x 1 columns]

In [171]:
from sklearn.neighbors import KNeighborsClassifier

In [172]:
knn = KNeighborsClassifier(n_neighbors=7)

In [176]:
X_train = train.drop('Survived', axis=1)
Y_train = train['Survived']

In [179]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [180]:
sk_predict = knn.predict(test)

In [181]:
sk_predict

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,

In [196]:
def score(x,y):
    count=0
    for i in range(len(y)):
        if x[i]==y[i]:
            count=count+1
    print(count)
    print(count/len(y))
    print('\n')
    print(count/len(y)*100)

In [199]:
score(new_predict,sk_predict)

301
0.7218225419664268


72.18225419664267
